inputs: 

  port: 
    description: 'Port for node application to run'
    default: 7001

  environment:
    description: 'Environment for node application'
    default: 'dev'

runs:

  using: "composite"

  steps:
    - name: step info
      run: echo Deployment to ${{ inputs.environment }} has started
      shell: cmd

    - name: stop existing service if it exists
      working-directory: python-greetings
      run: pm2 delete greetings-app-${{ inputs.environment }} & set "errorlevel=0"
      shell: cmd

    - name: start service
      working-directory: python-greetings
      run: pm2 start app.py --name greetings-app-${{ inputs.environment }} --port ${{ inputs.port }}
      shell: cmd
