name: python-greetings

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  install-pip-deps:
    name: install-pip-deps
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: 'mtararujs/python-greetings'
          path: 'python-greetings'
      - uses: ./.github/actions/install

  deploy-to-dev:
    name: deploy-to-dev
    runs-on: self-hosted
    needs: [install-pip-deps]

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: 'mtararujs/python-greetings'
          path: 'python-greetings'
      - uses: ./.github/actions/deploy
        with: 
          port: 7001
          environment: 'dev'

  tests-on-dev:
    name: tests-on-dev
    runs-on: self-hosted
    needs: [deploy-to-dev]

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: 'mtararujs/course-js-api-framework'
          path: 'course-js-api-framework'
      - uses: ./.github/actions/tests
        with: 
          environment: 'dev'
  
  
  deploy-to-staging:
    name: deploy-to-staging
    runs-on: self-hosted
    needs: [tests-on-dev]

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: 'mtararujs/python-greetings'
          path: 'python-greetings'
      - uses: ./.github/actions/deploy
        with: 
          port: 7002
          environment: 'staging'

  tests-on-staging:
    name: tests-on-staging
    runs-on: self-hosted
    needs: [deploy-to-staging]

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: 'mtararujs/course-js-api-framework'
          path: 'course-js-api-framework'
      - uses: ./.github/actions/tests
        with: 
          environment: 'staging'


  deploy-to-preprod:
    name: deploy-to-preprod
    runs-on: self-hosted
    needs: [tests-on-staging]

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: 'mtararujs/python-greetings'
          path: 'python-greetings'
      - uses: ./.github/actions/deploy
        with: 
          port: 7003
          environment: 'preprod'

  tests-on-preprod:
    name: tests-on-preprod
    runs-on: self-hosted
    needs: [deploy-to-preprod]

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: 'mtararujs/course-js-api-framework'
          path: 'course-js-api-framework'
      - uses: ./.github/actions/tests
        with: 
          environment: 'preprod'


  deploy-to-prod:
    name: deploy-to-prod
    runs-on: self-hosted
    needs: [tests-on-preprod]

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: 'mtararujs/python-greetings'
          path: 'python-greetings'
      - uses: ./.github/actions/deploy
        with: 
          port: 7004
          environment: 'prod'

  tests-on-prod:
    name: tests-on-prod
    runs-on: self-hosted
    needs: [deploy-to-prod]

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: 'mtararujs/course-js-api-framework'
          path: 'course-js-api-framework'
      - uses: ./.github/actions/tests
        with: 
          environment: 'prod'
